version: '3.8'

services:
  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - api-gateway

  # API Gateway Service
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - AI_SERVICE_URL=http://ai-service:8000
      - TAX_ENGINE_URL=http://tax-engine:5000
    depends_on:
      - ai-service

  # AI Service (LangChain + AWS Bedrock)
  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    environment:
      - AWS_DEFAULT_REGION=ap-south-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./data:/app/data

  # Redis for caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # MongoDB for data storage
  mongodb:
    image: mongo:latest
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
